### ISSUE TITLE
Use new React Context API

### ISSUE THREAD

**Issue by yordis** [callstack/react-theme-provider#22]

**Comment by souhe** [comment]
Hey @yordis 
We're using https://github.com/jamiebuilds/create-react-context polyfill to support older react versions

**Comment by yordis** [comment]
Sure, hopefully it gets remove in the near future.

Anyway npm deps could have more than one version of the same package for those who do not maintain their software and for does who do, we use the latest API.

But, there is the issue for paper trail so we dont forget about it

**Comment by satya164** [comment]
2.0 no longer uses the polyfill https://github.com/callstack/react-theme-provider/releases/tag/2.0.0
This can be closed
