### ISSUE TITLE
withTheme() swallows forwardedRef and prevents it from being passed to wrapped component.

### ISSUE THREAD

**Issue by tpoppen** [callstack/react-theme-provider#33]
When using the forwardedRef pattern from the React documentation, the forwarded ref is swallowed up by the HOC made by the withTheme method. 

the forwardedRef prop is pulled from the props on line 50 of createWithTheme.js, and is never passed on to the actual component.

**Comment by satya164** [comment]
Ouch. Must be a leftover. Can you send a PR removing that `forwardedRef`?

**Comment by tpoppen** [comment]
Yea I'll put a PR up for review sometime today or tomorrow.

**Comment by tpoppen** [comment]
@satya164 I found this commit on a branch called `disable-forward-refs` in the file I listed above. Is it desired to not allow forward refs?

**Comment by satya164** [comment]
Fixed in 2.0 https://github.com/callstack/react-theme-provider/releases/tag/2.0.0
This can be closed
