### ISSUE TITLE
add useTheme hook

### ISSUE THREAD

**Issue by sijad** [callstack/react-theme-provider#34]
currently it's possible to use `withTheme` HoC to add `theme` prop to custom components, but with `useTheme` hook it'd be easier to access to `theme`, usage would be similar to this:

```jsx
import * as React from 'react';
import { useTheme } from 'react-native-paper';

function MyComponent(props) {
  const { colors } = useTheme();
  return <Text style={{ color: colors.primary }}>Yo!</Text>;
}
```

using [useContext](https://reactjs.org/docs/hooks-reference.html#usecontext) it should be easy to add `useTheme` hook.

**Comment by satya164** [comment]
Added in 2.0 https://github.com/callstack/react-theme-provider/releases/tag/2.0.0
This can be closed
