### ISSUE TITLE
TypeError: Cannot read property 'getWrappedInstance' of undefined

### ISSUE THREAD

**Issue by zeevl** [callstack/react-theme-provider#35]
Using the following: 
 - react-native 0.58
 - mobx ^5.9.0
 - mobx-react ^5.4.3
 - react-native-paper ^2.7.0

When doing something akin to the following --
```
import React from 'react';
import { observer } from 'mobx-react/native';
import {
  withTheme
} from 'react-native-paper';

class SomeClass extends React.Component<Props> {
  render() {...}
}

export default withTheme(observer(SomeClass));
```

using that class throws, `TypeError: Cannot read property 'getWrappedInstance' of undefined.`

The place it's being thrown from is here -- https://github.com/callstack/react-theme-provider/blob/292e3c433c95e9335788d0c5b2dffedee26592c5/src/createWithTheme.js#L92

Apparently `this._root` doesn't exist on the component returned from `observable`.    I'm not sure what `_root` is supposed to come from or why it's assumed to be there?  

The object returned from `mobx-react#observable` works with other HOCs (i.e. react-jss) so it seems something special is being done here..?

**Comment by pranit123** [comment]
Hi. Did you find a solution to this?

**Comment by zeevl** [comment]
@pranit123 Sadly, no.  Ended up not using it all and instead exporting theme styles directly from another module.  Not ideal but it's working for now.

**Comment by shalehaha** [comment]
I ran into the same issue for one of my screen, then I finally figured out that the order of the annotation matters.
So at first, I had the following code which didn't work:
```
@inject('homeStore')
@observer
export default class HomeContainer extends React.Component<Props, State> 
```

Then I switched the sequence and it worked:
```
@observer
@inject('homeStore')
export default class HomeContainer extends React.Component<Props, State> 
```

Not sure which library should be blamed.

**Comment by satya164** [comment]
I just added a check for that in #32

**Comment by satya164** [comment]
2.0 is out now https://github.com/callstack/react-theme-provider/releases/tag/2.0.0
This can be closed
