### ISSUE TITLE
Module not found: Can't resolve '@callstack/theme-provider

### ISSUE THREAD

**Issue by kations** [callstack/react-theme-provider#43]
Hi,
I try to use this lib with https://github.com/DimiMikadze/create-react-library
but get this error.

"dependencies": {
    "@callstack/react-theme-provider": "^2.0.0",
    "color": "^3.1.0"
  },

other libs like color work without any problem.

My File:

import { createTheming } from "@callstack/theme-provider";
import defaultTheme from "./defaultTheme";

const { ThemeProvider, withTheme, useTheme } = createTheming(defaultTheme);

export { ThemeProvider, withTheme, useTheme };

**Comment by kations** [comment]
Your usage example is not correct arg... import { createTheming } from '@callstack/theme-provider';

**Comment by souhe** [comment]
It is fixed already! :)
